version: '3.8'

services:
  api:
    image: practica
    container_name: api_container
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=db:5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=123
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:13
    container_name: postgres_container
    environment:
      POSTGRES_DB: facturacion_AS
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
